/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Banger: typeof import('./src/components/onchain-game/banger.vue')['default']
    BlockContainer: typeof import('./src/components/layouts/BlockContainer.vue')['default']
    Boost: typeof import('./src/components/boost/boost.vue')['default']
    BoostRocket: typeof import('./src/components/main/BoostRocket.vue')['default']
    Boss: typeof import('./src/components/main/Boss.vue')['default']
    Button: typeof import('./src/components/button/button.vue')['default']
    ClaimInterface: typeof import('./src/components/utilityScreens/ClaimInterface.vue')['default']
    Column: typeof import('./src/components/layouts/Column.vue')['default']
    ErrorNotification: typeof import('./src/components/utilityScreens/ErrorNotification.vue')['default']
    ErrorScreen: typeof import('./src/components/utilityScreens/ErrorScreen.vue')['default']
    FeatureDisabled: typeof import('./src/components/utilityScreens/FeatureDisabled.vue')['default']
    FirstGame: typeof import('./src/components/onchain-game/firstGame.vue')['default']
    FirstSlide: typeof import('./src/components/preview/firstSlide.vue')['default']
    Footer: typeof import('./src/components/top/footer.vue')['default']
    FourthSlide: typeof import('./src/components/preview/fourthSlide.vue')['default']
    FullPage: typeof import('./src/components/layouts/FullPage.vue')['default']
    Game: typeof import('./src/components/onchain-game/game.vue')['default']
    GameCard: typeof import('./src/components/onchain-game/gameCard.vue')['default']
    Gem: typeof import('./src/components/main/gem.vue')['default']
    GemMenu: typeof import('./src/components/main/gemMenu.vue')['default']
    GridFour: typeof import('./src/components/layouts/GridFour.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ImprovementCard: typeof import('./src/components/boost/ImprovementCard.vue')['default']
    Loader: typeof import('./src/components/utilityScreens/Loader.vue')['default']
    MobileOnly: typeof import('./src/components/utilityScreens/MobileOnly.vue')['default']
    Name: typeof import('./src/components/squad/name.vue')['default']
    OrageButton: typeof import('./src/components/button/OrageButton.vue')['default']
    Page: typeof import('./src/components/layouts/Page.vue')['default']
    QuestCard: typeof import('./src/components/boost/QuestCard.vue')['default']
    Referral: typeof import('./src/components/referral/referral.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Screen1: typeof import('./src/components/onchain-game/screen1.vue')['default']
    SecondSlide: typeof import('./src/components/preview/secondSlide.vue')['default']
    ServiceWorks: typeof import('./src/components/utilityScreens/ServiceWorks.vue')['default']
    SocketFrame: typeof import('./src/components/main/socketFrame.vue')['default']
    SocketFrameNewVersion: typeof import('./src/components/main/socketFrameNewVersion.vue')['default']
    Squad: typeof import('./src/components/squad/squad.vue')['default']
    SquadCreate: typeof import('./src/components/squad/squadCreate.vue')['default']
    SquadTable: typeof import('./src/components/squad/SquadTable.vue')['default']
    Table: typeof import('./src/components/top/table.vue')['default']
    ThirdSlide: typeof import('./src/components/preview/thirdSlide.vue')['default']
    Title: typeof import('./src/components/layouts/Title.vue')['default']
    Top: typeof import('./src/components/top/top.vue')['default']
    TopByLeague: typeof import('./src/components/top/topByLeague.vue')['default']
    TwoColumns: typeof import('./src/components/layouts/TwoColumns.vue')['default']
    UserInfoCard: typeof import('./src/components/main/userInfoCard.vue')['default']
  }
}
